### ISSUE TITLE
about europe

### ISSUE THREAD

**Issue by Stockard** [Glacier-Ice/data-sci-api#22]
https://github.com/Glacier-Ice/data-sci-api/blob/master/docs/docs/EN/resources.md

@emptymalei   It's worth noticing that even between OECD countries, the level of information disclosure between countries varies. 你介意稍微扩展一下这部分吗?我不太知道欧洲的情况.

**Comment by emptymalei** [comment]
We already have transparancy in some regions of the world. The African union (AU) and the European union (EU) publish the pandemic data for every countries everyday. Many European countries publish the detailed data. However, it's worth noticing that even between OECD countries, the level of information disclosure between countries varies. Not to mention other countries that has more diverged economic or social nature.
